### ISSUE TITLE
Cannot edit any files with ki

### ISSUE THREAD

**Issue by iljarotar** [ki-editor/ki-editor#248]
Hello! I would like to try out the ki editor, However, unfortunately I'm unable to open any files with it as it always panics with:

```bash
$ ki edit README.md
thread 'main' panicked at src/main.rs:55:16:
called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I installed the editor following the installation instructions at [ki-editor.github.io/ki-editor/installation](https://ki-editor.github.io/ki-editor/installation.html).

OS information:

```bash
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

Running ki with `RUST_BACKTRACE=full` returns

```bash
thread 'main' panicked at src/main.rs:55:16:
called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)
stack backtrace:
   0:     0x5818344d51d6 - std::backtrace_rs::backtrace::libunwind::trace::hbee8a7973eeb6c93
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x5818344d51d6 - std::backtrace_rs::backtrace::trace_unsynchronized::hc8ac75eea3aa6899
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5818344d51d6 - std::sys_common::backtrace::_print_fmt::hc7f3e3b5298b1083
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x5818344d51d6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbb235daedd7c6190
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x581834505960 - core::fmt::rt::Argument::fmt::h76c38a80d925a410
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/rt.rs:142:9
   5:     0x581834505960 - core::fmt::write::h3ed6aeaa977c8e45
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/mod.rs:1120:17
   6:     0x5818344d0def - std::io::Write::write_fmt::h78b18af5775fedb5
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/io/mod.rs:1810:15
   7:     0x5818344d4fb4 - std::sys_common::backtrace::_print::h5d645a07e0fcfdbb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x5818344d4fb4 - std::sys_common::backtrace::print::h85035a511aafe7a8
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x5818344d6a47 - std::panicking::default_hook::{{closure}}::hcce8cea212785a25
  10:     0x5818344d67a9 - std::panicking::default_hook::hf5fcb0f213fe709a
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:292:9
  11:     0x5818344d6ed8 - std::panicking::rust_panic_with_hook::h095fccf1dc9379ee
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:779:13
  12:     0x5818344d6db2 - std::panicking::begin_panic_handler::{{closure}}::h032ba12139b353db
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:657:13
  13:     0x5818344d56d6 - std::sys_common::backtrace::__rust_end_short_backtrace::h9259bc2ff8fd0f76
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x5818344d6b10 - rust_begin_unwind
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
  15:     0x581833d16e15 - core::panicking::panic_fmt::h784f20a50eaab275
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
  16:     0x581833d17303 - core::result::unwrap_failed::h03d8a5018196e1cd
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1649:5
  17:     0x58183402244f - core::result::Result<T,E>::unwrap::hffd837bad3a45895
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1073:23
  18:     0x58183402244f - ki::main::ha607b532978f3f0a
                               at /home/ilja/git/github.com/ki-editor/ki-editor/src/main.rs:55:5
  19:     0x581833e111d3 - core::ops::function::FnOnce::call_once::hbc6c604f8e9bec0c
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
  20:     0x581833e111d3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h8747e4dfc2ff22ad
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:155:18
  21:     0x581834023609 - std::rt::lang_start::{{closure}}::h6b359897bec5d3f0
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:166:18
  22:     0x5818344c8041 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h37600b1e5eea4ecd
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:284:13
  23:     0x5818344c8041 - std::panicking::try::do_call::hb4bda49fa13a0c2b
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  24:     0x5818344c8041 - std::panicking::try::h8bbf75149211aaaa
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  25:     0x5818344c8041 - std::panic::catch_unwind::h8c78ec68ebea34cb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  26:     0x5818344c8041 - std::rt::lang_start_internal::{{closure}}::hffdf44a19fd9e220
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:48
  27:     0x5818344c8041 - std::panicking::try::do_call::hcb3194972c74716d
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  28:     0x5818344c8041 - std::panicking::try::hcdc6892c5f0dba4c
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  29:     0x5818344c8041 - std::panic::catch_unwind::h4910beb4573f4776
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  30:     0x5818344c8041 - std::rt::lang_start_internal::h6939038e2873596b
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:20
  31:     0x5818340235fc - main
  32:     0x75ede9e29d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  33:     0x75ede9e29e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  34:     0x581833d17655 - _start
  35:                0x0 - <unknown>
```

Unfortunately, I don't know rust. So investigating on the issue by myself will probably take a long time. I would appreciate any help.

**Comment by wongjiahau** [comment]
Hi @iljarotar thanks for trying! That is very odd, have you tried running only `ki` at your repository root instead of `ki edit README.md`?

**Comment by iljarotar** [comment]
Thanks for the quick reply. Yes, I have tried running 

```bash
$ ki
thread 'main' panicked at src/main.rs:55:16:
called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
```bash
$ ki log
thread 'main' panicked at src/main.rs:55:16:
called `Result::unwrap()` on an `Err` value: Cannot canonicalize path: "/home/ilja/.cache/ki/ki.log". Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
and

```bash
$ ki in .
thread 'main' panicked at src/main.rs:55:16:
called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Running `ki grammar fetch` and `ki grammar build` worked without errors. `ki highlight-query` commands also worked.
The error returned from `ki log` makes sense, because there is no `.cache/ki/ki.log` file yet. But receiving a panic from that is unexpected.

**Comment by iljarotar** [comment]
This is mysterious.. I just tried it again, and suddenly it worked. I can't explain what was different from the other times...
Anyway, I'm glad I can give it a try now.

**Comment by wongjiahau** [comment]
That's rather perplexing... anyway let me know if you need any guidance or help!

**Comment by iljarotar** [comment]
I figured out what caused the problem. Just installed ki on a different computer and had the same problem with not being able to open a file. Turns out it was the missing `~/.cache/ki/ki.log` file that caused the panic. After creating the directory and file everything works fine.

**Comment by mabbamOG** [comment]
yes having same issue. basically trying out this editor is halfway impossible for 99% of people since it will immediately crash, and it crashes in the very first few lines of the program because of some file path stuff.  i tried adding `~/.cache/ki/ki.log` and it started up

**Comment by wongjiahau** [comment]
Thanks for the report I will fix it soon, at the same time how did you guys learn about this editor?

**Comment by iljarotar** [comment]
> Yea Ki is not optimized for performance yet, how large is the repository in which you opened Ki in terms of line of codes?
Or is the file very large?

I opened it in different repositories, among them the ki-editor repository itself.

> What did you press specifically after pressing g?

I pressed `gg` and didn't understand how to return back to the normal view.

**Comment by wongjiahau** [comment]
> I pressed gg and didn't understand how to return back to the normal view.

I think I know what's the problem now, because `gg` is not going to the first line like Vim, `gg` sets the current selection mode into Global Git Hunks, and if the repository contains no diff, then pressing hjkl does nothing.

You have to change the selection mode to another selection mode to make hjkl works again, for example, you can press `u` to get into the Column selection mode, and in `u` hjkl works like Vim's hjkl.
Other useful selection modes are `e` (Line), `w` (Word), `n` (Syntax Tree Node) etc.

**Comment by wongjiahau** [comment]
@iljarotar Regarding the lag, can you tail Ki’s log file after you open a file with the editor and check if the log file is being spammed indefinitely?

If that's the case that might be an existing bug with the LSP connection which also affects me sometimes.

**Comment by wongjiahau** [comment]
@mabbamOG Do you face the lag as well?

**Comment by mabbamOG** [comment]
I tried it only a little bit, so I don't know about the lag.

I found out about ki the same way as the other guy: through helix + searching for file tree. I went through the wiki but found it too complicated to understand. If the keybindings are really more consistent, you should be able to explain the basics in a one pager and people should pick it up really fast. Basically the main reason (most) people use vim derivates instead of eMacs is bc vim keybindings are honestly easier to learn, and if something is easier to learn u can remember it, and be more powerful with it. Just a tip. Me personally I don't use terminal editors that much anymore but wanted to play around with neovim/helix and I liked the idea of even better keybding defaults that ki promises.

**Comment by wongjiahau** [comment]
@mabbamOG thanks for the feedback, I think I got where you're coming from, I might have to create a tutorial for that.
