### ISSUE TITLE
Panic if marksman is not installed

### ISSUE THREAD

**Issue by ilyagr** [ki-editor/ki-editor#313]
I'm using `ki` just compiled from HEAD, on ARM Mac OS. I am in the root of the ki repo. I get:

```console
$ RUST_BACKTRACE=1 ki edit docs/src/normal-mode/movement-actions.md
thread 'main' panicked at src/main.rs:56:16:
                                            called `Result::unwrap()` on an `Err` value: screen.run Failed to spawn the command: ProcessCommand { command: "marksman", args: ["server"] } with error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
                          stack backtrace:
                                             0: rust_begin_unwind
                                                                              at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:652:5
                                              1: core::panicking::panic_fmt
                                                                                        at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/panicking.rs:72:14
                                                         2: core::result::unwrap_failed
                                                                                                    at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/result.rs:1679:5
                                                                   3: core::result::Result<T,E>::unwrap
                                                                                                                    at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/result.rs:1102:23
                                                                                    4: ki::main
                                                                                                            at ./src/main.rs:56:5
            5: core::ops::function::FnOnce::call_once
                                                                  at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/ops/function.rs:250:5
                                   note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Comment by wongjiahau** [comment]
Ah, this is an old friend, let me fix it.

**Comment by ilyagr** [comment]
That might be good, but it would also be good to propagate the error if the
lsp failed to run for some other reason and report the failure to the user.
