### ISSUE TITLE
bug(global_replace): replacing with strict regex crash

### ISSUE THREAD

**Issue by wongjiahau** [ki-editor/ki-editor#417]
## Steps
1. Run a global strict regex search with pattern that contains ".".
2. Run global replace using any pattern.
3. Crashes

## Log
```
thread '<unnamed>' panicked at /Users/wongjiahau/.cargo/registry/src/index.crates.io-6f17d22bba15001f/fancy-regex-0.14.0/src/lib.rs:1073:45:
called `Result::unwrap()` on an `Err` value: RuntimeError(BacktrackLimitExceeded)
stack backtrace:
   0: rust_begin_unwind
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/result.rs:1679:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/result.rs:1102:23
   4: fancy_regex::Regex::replacen
             at /Users/wongjiahau/.cargo/registry/src/index.crates.io-6f17d22bba15001f/fancy-regex-0.14.0/src/lib.rs:1073:9
   5: fancy_regex::Regex::replace_all
             at /Users/wongjiahau/.cargo/registry/src/index.crates.io-6f17d22bba15001f/fancy-regex-0.14.0/src/lib.rs:1059:14
   6: ki::buffer::Buffer::replace
             at /Users/wongjiahau/repos/ki-editor/src/buffer.rs:864:38
   7: ki::list::grep::replace::{{closure}}
   8: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/alloc/src/boxed.rs:2077:9
   9: ki::list::WalkBuilderConfig::run::{{closure}}::{{closure}}
             at /Users/wongjiahau/repos/ki-editor/src/list/mod.rs:101:49
  10: <alloc::boxed::Box<F,A> as core::ops::function::FnMut<Args>>::call_mut
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/alloc/src/boxed.rs:2070:9
  11: <ignore::walk::FnVisitorImp as ignore::walk::ParallelVisitor>::visit
             at /Users/wongjiahau/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ignore-0.4.20/src/walk.rs:1177:9
  12: ignore::walk::Worker::run_one
             at /Users/wongjiahau/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ignore-0.4.20/src/walk.rs:1445:20
  13: ignore::walk::Worker::run
             at /Users/wongjiahau/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ignore-0.4.20/src/walk.rs:1434:38
  14: ignore::walk::WalkParallel::visit::{{closure}}::{{closure}}
             at /Users/wongjiahau/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ignore-0.4.20/src/walk.rs:1299:41
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at /Users/wongjiahau/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ignore-0.4.20/src/walk.rs:1302:31:
called `Result::unwrap()` on an `Err` value: Any { .. }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/result.rs:1679:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/result.rs:1102:23
   4: ignore::walk::WalkParallel::visit::{{closure}}
             at /Users/wongjiahau/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ignore-0.4.20/src/walk.rs:1302:17
   5: std::thread::scoped::scope::{{closure}}
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/thread/scoped.rs:152:51
   6: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/panic/unwind_safe.rs:272:9
   7: std::panicking::try::do_call
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:559:40
   8: std::panicking::try
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:523:19
   9: std::panic::catch_unwind
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panic.rs:149:14
  10: std::thread::scoped::scope
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/thread/scoped.rs:152:18
  11: ignore::walk::WalkParallel::visit
             at /Users/wongjiahau/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ignore-0.4.20/src/walk.rs:1285:9
  12: ignore::walk::WalkParallel::run
             at /Users/wongjiahau/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ignore-0.4.20/src/walk.rs:1209:9
  13: ki::list::WalkBuilderConfig::run
             at /Users/wongjiahau/repos/ki-editor/src/list/mod.rs:80:9
  14: ki::list::grep::replace
             at /Users/wongjiahau/repos/ki-editor/src/list/grep.rs:41:8
  15: ki::app::App<T>::global_replace
             at /Users/wongjiahau/repos/ki-editor/src/app.rs:1264:30
  16: ki::app::App<T>::handle_dispatch
             at /Users/wongjiahau/repos/ki-editor/src/app.rs:695:34
  17: ki::app::App<T>::handle_dispatches
             at /Users/wongjiahau/repos/ki-editor/src/app.rs:394:13
  18: ki::app::App<T>::handle_dispatches_result
             at /Users/wongjiahau/repos/ki-editor/src/app.rs:386:9
  19: ki::app::App<T>::handle_event
             at /Users/wongjiahau/repos/ki-editor/src/app.rs:232:17
  20: ki::app::App<T>::run
             at /Users/wongjiahau/repos/ki-editor/src/app.rs:173:45
  21: ki::run
             at /Users/wongjiahau/repos/ki-editor/src/main.rs:102:5
  22: ki::cli::cli
  23: ki::main
             at /Users/wongjiahau/repos/ki-editor/src/main.rs:60:5
  24: core::ops::function::FnOnce::call_once
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Comment by wongjiahau** [comment]
The Steps in the previous comment are incorrect, the crash is due to running the replacement in a very large SVG file (1.8 MB)
